<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Ringkasan - {{ $materi->judul }}</title>
    <style>
        body { 
            font-family: 'DejaVu Sans', Arial, sans-serif; 
            line-height: 1.6;
            color: #333;
            font-size: 12px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 25px; 
            border-bottom: 2px solid #4F46E5; 
            padding-bottom: 15px; 
        }
        .header h1 { 
            color: #4F46E5; 
            margin: 0; 
            font-size: 20px;
        }
        .header h2 { 
            color: #666; 
            margin: 5px 0; 
            font-size: 16px;
            font-weight: normal;
        }
        .summary-content { 
            margin: 20px 0; 
            white-space: pre-line;
            background: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            border-left: 4px solid #4F46E5;
        }
        .footer { 
            margin-top: 30px; 
            text-align: center; 
            font-size: 10px; 
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .info-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        .badge {
            background: #4F46E5;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 10px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📚 Ringkasan Materi</h1>
        <h2>{{ $materi->judul }}</h2>
        <div class="info-row">
            <div>
                <strong>Kelas:</strong> {{ $kelas->nama_kelas }}<br>
                <strong>Dibuat:</strong> {{ $materi->summary_generated_at->format('d M Y H:i') }}
            </div>
            <div>
                <span class="badge">AI Generated</span>
            </div>
        </div>
    </div>
    
    <div class="summary-content">
        {{ $materi->summary }}
    </div>
    
    <div class="footer">
        <p>Generated by eduSPACE • Powered by Google Gemini AI • {{ date('d M Y H:i') }}</p>
    </div>
</body>
</html>